services:
  blazorapptest1:
    image: custom-blazor-app-test1
    build:
      context: .
      dockerfile: BlazorAppTest1\Dockerfile
    ports:
    - name: web
      target: 80
      host_ip: 127.0.0.1
      published: "8080"
      protocol: tcp
      app_protocol: http
      mode: host

    - name: web-secured
      target: 443
      host_ip: 127.0.0.1
      published: "8081"
      protocol: tcp
      app_protocol: https
      mode: host