services:
  blazorapptest1:
    image: custom-blazor-app-test1
    build:
      context: .
      dockerfile: BlazorAppTest1\Dockerfile
    ports:
    - name: web
      target: 5000
      host_ip: 0.0.0.0
      published: "80"
      protocol: tcp
      app_protocol: http
      mode: host

    - name: web-secured
      target: 5001
      host_ip: 0.0.0.0
      published: "443"
      protocol: tcp
      app_protocol: https
      mode: host